import Functions.Tint
import Functions.Tbool
import Functions.TopLogic
import Functions.TopArithm
import Functions.Tif
import Functions.Tvar
import Functions.Tfun
import Functions.Tapp
import Functions.Tlet
import Functions.Tletrec
import Functions.Traise
import Functions.Ttry
import Functions.Thd
import Functions.Ttl
import Functions.Tisempty
